-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.barang
(
    kode_barang character varying COLLATE pg_catalog."default" NOT NULL,
    nama_barang character varying COLLATE pg_catalog."default",
    kemasan character varying COLLATE pg_catalog."default",
    harga integer,
    nama_tipe character varying COLLATE pg_catalog."default",
    kode_brand integer,
    brand character varying COLLATE pg_catalog."default",
    CONSTRAINT barang_pkey PRIMARY KEY (kode_barang)
);

CREATE TABLE IF NOT EXISTS public.invoice
(
    id_invoice character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT invoice_pkey PRIMARY KEY (id_invoice)
);

CREATE TABLE IF NOT EXISTS public.pelanggan
(
    id_customer character varying COLLATE pg_catalog."default" NOT NULL,
    level character varying COLLATE pg_catalog."default",
    nama character varying COLLATE pg_catalog."default",
    id_cabang_sales character varying COLLATE pg_catalog."default",
    cabang_sales character varying COLLATE pg_catalog."default",
    id_distributor character varying COLLATE pg_catalog."default",
    "group" character varying COLLATE pg_catalog."default",
    CONSTRAINT pelanggan_pkey PRIMARY KEY (id_customer)
);

CREATE TABLE IF NOT EXISTS public.penjualan
(
    id_invoice character varying COLLATE pg_catalog."default",
    tanggal character varying COLLATE pg_catalog."default",
    id_customer character varying COLLATE pg_catalog."default",
    id_barang character varying COLLATE pg_catalog."default",
    jumlah_barang integer,
    unit character varying COLLATE pg_catalog."default",
    harga integer,
    mata_uang character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT customer_fkey FOREIGN KEY (id_customer)
    REFERENCES public.pelanggan (id_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT invoice_fkey FOREIGN KEY (id_invoice)
    REFERENCES public.invoice (id_invoice) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT kode_barang_fkey FOREIGN KEY (id_barang)
    REFERENCES public.barang (kode_barang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;